### ISSUE TITLE
PREPFAN

### ISSUE THREAD

**Issue by thejmazz** [hyginn/Ontoscope#3]
Prepare FANTOM profile resource

**Comment by biodim** [comment]
The fantom module has "built in" normalizing. 

Take a look at the output:
https://github.com/hyginn/Ontoscope/tree/master/fantom_import/RData_Samples

and see if it is acceptable. The fantomCounts.RData is the "FANTOMdat" in the project workflow. 

EDIT: I am going to close this, since I think it is done. Let me know if you want the data in a different format
