### ISSUE TITLE
TRRUST

### ISSUE THREAD

**Issue by thejmazz** [hyginn/Ontoscope#6]

**Comment by biodim** [comment]
I am closing this, since I couldn't implement a better weighting algorithm, so "Betweenness Centrality" it will be

This means the TRRUST Network Submodule has 2 potential functions:

1) As a score "boost" for the RANK module (refer to the "weave" folder)

2) As a visualizer of the final result. If you take a look at mogrify:

http://www.mogrify.net/joint_reprogrammers?source_ont=FF:0000004&target_ont=FF:0010019

they have a graph of gene interactions. We can also build a similar-ish graph with the TRRUST network sub-module
